# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

#Fabric properties
minecraft_version    = 26.2
loader_version       = 0.19.3

#Mod properties 
mod_version          = 1.7.0
maven_group          = com.craftycorvid.improvedSigns
archives_base_name   = improved-signs

#Dependencies
fabric_api_version   = 0.156.0+26.2
